# Generated by Django 3.1.4 on 2020-12-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='from_guide',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='folder',
            name='serie',
            field=models.CharField(default='Incomplete', max_length=10),
        ),
        migrations.AlterField(
            model_name='folder',
            name='to_guide',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
