# Generated by Django 3.1.4 on 2020-12-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20201208_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
